version: '3.3'
services:
  # Trial MariaDB-tjeneste
  trial-mariadb:
    image: mariadb:latest
    container_name: trial-mariad
    environment:
      MARIADB_ROOT_PASSWORD: Data1500&v25
    restart: unless-stopped
    volumes: 
      - ./data1500-mysql-data:/var/lib/mysql:Z
      - ./data1500-mysql-initdb:/docker-entrypoint-initdb.d/:ro
    networks:
      - data1500-network

  http-server:
    container_name: java-http-server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - trial-mariadb
    environment:
      DB_URL: "jdbc:mysql://trial-mariadb:3306/kap10?useSSL=false&serverTimezone=Europe/Oslo"
      DB_USER: "u_kap10_25"
      DB_PASSWORD: "123.Kap10#"
    ports:
      - "5005:5005"
    networks:
      - data1500-network

networks:
  data1500-network:
